version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: swimmers_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: swimmers
    ports:
      - "5434:5432"
    volumes:
      - swimmers_db_data:/var/lib/postgresql/data

volumes:
  swimmers_db_data:
